server:
  port: 8081

management:
  endpoint:
    health:
      # 为health端点配置显示详情
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露metrics端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: "*"
spring:
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  application:
    name: provider-user
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://admin:admin@peer1:8761/eureka/,http://admin:admin@peer2:8762/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就回注册主机名到eureka server
    prefer-ip-address: true
